[package]
name = "rsjson"
version = "1.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.154"
serde_json = "1.0.116"
serde = { version = "1.0.200", features = ["derive"] }